# Generated by Django 2.2.16 on 2023-06-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230607_2220'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favourite',
            name='unique_favourite',
        ),
        migrations.AddConstraint(
            model_name='favourite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_favorites'),
        ),
    ]
