# Generated by Django 2.2.16 on 2023-05-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230527_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'verbose_name': ('Ингридиенты рецепта',), 'verbose_name_plural': 'Ингридиенты рецептов'},
        ),
        migrations.AlterModelOptions(
            name='tagrecipe',
            options={'ordering': ['tag'], 'verbose_name': ('Теги рецепта',), 'verbose_name_plural': 'Теги рецептов'},
        ),
    ]
